apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - port: 6000
      protocol: TCP
      targetPort: 5000
      # nodePort: 6443
      # nodePort: 30900
  selector:
    podLabel: frontendPod
  type: LoadBalancer
