apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      podLabel: frontendPod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        podLabel: frontendPod
    spec:
      containers:
        - image: ghcr.io/eficode-academy/quotes-flask-frontend:release
          name: quotes-flask-frontend
          ports:
            - containerPort: 5000
          resources: {}
          env:
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: backend_host
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: backend_port
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

