apiVersion: v1
kind: Pod
metadata:
  labels:
    run: backend
  name: backend
spec:
  containers:
  - image: ghcr.io/eficode-academy/flask-quotes-backend:release
    name: flask-quotes-backend
    resources: {}
  restartPolicy: Always