apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: ghcr.io/eficode-academy/quotes-flask-frontend:release
    ports:
    - containerPort: 5000
