apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-pvc-volume # name we can reference below in container
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: config-volume
          configMap:
            name: postgres-config
        - name: secret-volume
          secret:
            secretName: postgres-secret
      containers:
        - image: docker.io/library/postgres:14.3
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pvc-volume
            - mountPath: /etc/config
              name: config-volume
            - mountPath: /etc/secret
              name: secret-volume
      
status: {}
