apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: ghcr.io/eficode-academy/flask-quotes-frontend:release
    name: frontend
    resources: {}
    env:
      - name: backend_host
        value: backend
      - name: backend_port
        value: "5000"
  restartPolicy: Always