apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deployement
  name: backend-deployement
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend-deployement
  template:
    metadata:
      labels:
        app: backend-deployement
    spec:
      containers:
      - image: ghcr.io/eficode-academy/quotes-flask-backend:release
        name: quotes-flask-backend
