apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: ghcr.io/eficode-academy/flask-quotes-frontend:release
    name: frontend
    resources: {}
    env:
      - name: BACKEND_SVC_HOST
        value: backend
      - name: BACKEND_SVC_PORT
        value: "5000"
  restartPolicy: Always